name: CBF

dependencies:
  - python=3.8
  - tensorflow=2.8.2
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tensorboard
  - setuptools=65.5.0
  - pip=21
  - cython<3
  - pip:
    - ray[tune,rllib]==1.13.0
    - gym==0.21.0